### ISSUE TITLE
cloudview doesn't work behind ssl-termination

### ISSUE THREAD

**Issue by ScrumpyJack** [jfcherng-roundcube/plugin-cloudview#12]
roundcude 1.4.8
cloudview latest

To build the URL to view the attachment, cloudview uses RoundCubeHelper::getSiteUrl but this doesn't seem to work behind ssl-termination (in my case traefik) that adds the ssl proxy header X-Forwarded-Proto: "https" 

Can we have an option for force https:// in cloudview directly?

**Comment by jfcherng** [comment]
> Can we have an option for force https:// in cloudview directly?

Sure. Sounds like a valid request to me.

But I wonder if I setup RC as a local site and access it from outside via a reverse proxy, will the returned query URL correct rather than something like `127.0.0.1:xxxx/xxxxx...`?

**Comment by jfcherng** [comment]
Are you able to try this patch?
https://github.com/jfcherng-roundcube/plugin-cloudview/commit/04ad9f56005cb09be506d4c845d05000bc1930c5

**Comment by ScrumpyJack** [comment]
Yes that worked.

I had to add the full path, as I serve under https://example.com/roundcube and the url builder missed out /roundcube

**Comment by jfcherng** [comment]
> Yes that worked.
> 
> I had to add the full path, as I serve under [example.com/roundcube](https://example.com/roundcube) and the url builder missed out /roundcube

Great! `0.6.11` has been released.
