### ISSUE TITLE
server error (internal server error) Roundcube

### ISSUE THREAD

**Issue by TheEgyptianDevelopers** [jfcherng-roundcube/plugin-cloudview#15]
server error (internal server error) Roundcube

when I click cloudview it gives me this error message

**Comment by jfcherng** [comment]
Detail error trace would be needed in order to fix it.

**Comment by TheEgyptianDevelopers** [comment]
how to do the error trace please, or where I can find it?

**Comment by jfcherng** [comment]
There should be some error messages in RoundCube's log file(s).

**Comment by TheEgyptianDevelopers** [comment]
it opens the popup now, but it gives this message when I check the FTP I find the file, when I use Microsoft office and even when u choose google to view, it said cant view

File not found
The URL of the original file is not valid or the document is not publicly accessible.
Verify the URL is correct, then contact the document owner.

https://docs.google.com/viewer?embedded=true&url=https%3A%2F%2Fserver1.***.com%2Fcpsess4273829571%2F3rdparty%2Froundcube%2Fplugins%2Fcloudview%2Ftemp%2F1201%2Fa953a816542427df0a6b9668362e0834.pptx
![Screen Shot 2021-01-20 at 12 20 14 PM](https://user-images.githubusercontent.com/6382309/105161304-e5a46b80-5b19-11eb-908d-84d576f38d61.png)
![Screen Shot 2021-01-20 at 12 15 24 PM](https://user-images.githubusercontent.com/6382309/105161321-eb01b600-5b19-11eb-9e57-3ac1c5ea8308.png)

**Comment by jfcherng** [comment]
I guess that the `temp` directory under `cloudview`'s directory is not public accessible due to your server(I mean Apache/NGINX) config.

**Comment by TheEgyptianDevelopers** [comment]
so how to give the public access to this folder?

**Comment by jfcherng** [comment]
- Do you know what web server you are using?
- What if you remove the `temp|` from https://github.com/roundcube/roundcubemail/blob/375d6680647bcd422519fcd4b8f8ee90cec3b0be/.htaccess#L13

**Comment by TheEgyptianDevelopers** [comment]
>     * Do you know what web server you are using?
> 
>     * What if you remove the `temp|` from https://github.com/roundcube/roundcubemail/blob/375d6680647bcd422519fcd4b8f8ee90cec3b0be/.htaccess#L13 ?

i did already remove temp | from htacess file, I use Namecheap servers ( CENTOS 7.9 [server1]  )

**Comment by jfcherng** [comment]
Having no idea what is blocking it from being public at this moment.

**Comment by TheEgyptianDevelopers** [comment]
> Having no idea what is blocking it from being public at this moment.

Thank you so much for ur efforts, I will search again and if it fixed, I will add it here so anyone who has the same issue can find the solution easy

we all appreciate ur work, thank you

**Comment by rgbGlobus** [comment]
This solution helped me:
you need to go to the mail not by the internal ip address (for example 192.168.88.3/mail), but by the external address of your mail, for example https://mail.google.com/mail

**Comment by TheEgyptianDevelopers** [comment]
> This solution helped me:
> you need to go to the mail not by the internal ip address (for example 192.168.88.3/mail), but by the external address of your mail, for example https://mail.google.com/mail

Thank you so much and I will try it and give u the updates

**Comment by jfcherng** [comment]
> This solution helped me:
> you need to go to the mail not by the internal ip address (for example 192.168.88.3/mail), but by the external address of your mail, for example [mail.google.com/mail](https://mail.google.com/mail)

That's a good missing point that I had never thought. I will add it to the readme. Thanks!

**Comment by jfcherng** [comment]
Can't used with internal IP since public external service can't retrieve the file for rendering.
