### ISSUE TITLE
Error on RC 1.6.1

### ISSUE THREAD

**Issue by Dmitry422** [jfcherng-roundcube/plugin-cloudview#18]
Jan 29 19:05:11 mail roundcube: PHP Fatal error:  Uncaught Error: Call to a member function get_message_part() on null in /var/www/html/webmail/plugins/cloudview/cloudview.php:344
Jan 29 19:05:11 mail roundcube: Stack trace:
Jan 29 19:05:11 mail roundcube: #0 /var/www/html/webmail/plugins/cloudview/cloudview.php(213): cloudview->saveAttachmentToLocal()
Jan 29 19:05:11 mail roundcube: #1 /var/www/html/webmail/program/lib/Roundcube/rcube_plugin_api.php(575): cloudview->viewAction()
Jan 29 19:05:11 mail roundcube: #2 /var/www/html/webmail/program/include/rcmail.php(255): rcube_plugin_api->exec_action()
Jan 29 19:05:11 mail roundcube: #3 /var/www/html/webmail/index.php(278): rcmail->action_handler()
Jan 29 19:05:11 mail roundcube: #4 {main}
Jan 29 19:05:11 mail roundcube:   thrown in /var/www/html/webmail/plugins/cloudview/cloudview.php on line 344

**Comment by jfcherng** [comment]
This should've been fixed in https://github.com/jfcherng-roundcube/plugin-cloudview/commit/4e6db5642e7d592cc25c86be2c0c1c5c25044b63 and released as `0.6.16`.
