### ISSUE TITLE
Not an ussue but Ive got internal server error, pls help

### ISSUE THREAD

**Issue by Kea-hash** [jfcherng-roundcube/plugin-cloudview#23]
Hello!
Ive installed plugin-cloudview by composer as instruction said. But have internal server error when try to view xls-attacment there is log. It's host on Ubuntu+Apache2
[23-Oct-2023 19:58:04 UTC] PHP Warning:  fopen(/var/www/html/roundcube/plugins/cloudview/temp/8/a313fd14cd97e1afe5729f1>
[23-Oct-2023 19:58:04 UTC] PHP Fatal error:  Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resour>
Stack trace:
#0 /var/www/html/roundcube/plugins/cloudview/cloudview.php(345): fclose()
#1 /var/www/html/roundcube/plugins/cloudview/cloudview.php(213): cloudview->saveAttachmentToLocal()
#2 /var/www/html/roundcube/program/lib/Roundcube/rcube_plugin_api.php(577): cloudview->viewAction()
#3 /var/www/html/roundcube/program/include/rcmail.php(255): rcube_plugin_api->exec_action()
#4 /var/www/html/roundcube/index.php(278): rcmail->action_handler()
#5 {main}
  thrown in /var/www/html/roundcube/plugins/cloudview/cloudview.php on line 345

**Comment by Kea-hash** [comment]
Ive also add to apache2.conf those lines
#cloudview
<Directory /var/www/html/roundcube/plugins/cloudview/temp>
         Options Indexes FollowSymLinks
         AllowOverride None
         Require all granted
</Directory>
#cloudview

**Comment by Kea-hash** [comment]
and remove "temp" from .htaccess from roundcube home dit

**Comment by Kea-hash** [comment]
Internal Server error still persists

**Comment by jfcherng** [comment]
> [23-Oct-2023 19:58:04 UTC] PHP Fatal error: Uncaught TypeError: fclose(): Argument https://github.com/jfcherng-roundcube/plugin-cloudview/pull/1 ($stream) must be of type resour>

This error msg seems to be edited?

**Comment by Kea-hash** [comment]
Thanks for fast answer, error was in folder permissions.

**Comment by Kea-hash** [comment]
Completed

**Comment by jfcherng** [comment]
> Thanks for fast answer, error was in folder permissions.

Interesting. I thought it will emit error earlier when doing `fopen()`...

**Comment by Kea-hash** [comment]
maybe you know is there plugin for roundcube for preview .mp4 attachments?

**Comment by jfcherng** [comment]
Any modern web browsers should play it. It's just not code to support it here.

**Comment by Kea-hash** [comment]
It's work! Cool, thank you very much! You need to add it to release :)

**Comment by jfcherng** [comment]
`0.6.18` has been released.
