### ISSUE TITLE
pls add an Ukrainian localization

### ISSUE THREAD

**Issue by Kea-hash** [jfcherng-roundcube/plugin-cloudview#25]
attached
[cl_v_ua_UA.zip](https://github.com/jfcherng-roundcube/plugin-cloudview/files/13367559/cl_v_ua_UA.zip)

**Comment by jfcherng** [comment]
Done. Thanks. https://github.com/jfcherng-roundcube/plugin-cloudview/commit/7d2d8bf4d5eda9281d22891c97cd684ec1f8f359

**Comment by jfcherng** [comment]
`0.6.19` has been released.
